default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %> # Herokuの自動生成URLを使用

development:
  <<: *default
  database: science_app_development

test:
  <<: *default
  database: science_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # 本番環境もHerokuのURLを使用