default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: science_app_development

test:
  <<: *default
  database: science_app_test

production:
  <<: *default
  database: science_app_production
  username: <%= ENV['DB_USERNAME_PRODUCTION'] %>
  password: <%= ENV['DB_PASSWORD_PRODUCTION'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

  cable:
    <<: *default
    database: science_app_production_cable
    username: <%= ENV['DB_USERNAME_PRODUCTION'] %>
    password: <%= ENV['DB_PASSWORD_PRODUCTION'] %>
    host: <%= ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['DB_PORT'] || 5432 %>